### PR TITLE
Backlight change when computer is idle

### PR DESCRIPTION
**Pull request by selairi**
Please visit: 

[https://github.com/lxqt/lxqt-powermanagement/issues/188](https://github.com/lxqt/lxqt-powermanagement/issues/188)

### CODE REVIEW

**Comment by tsujan** [comment]
I'm afraid it didn't work here. I upgraded liblxqt to your latest commit but the backlight didn't change after 1 sec., 10 sec., or 1 min. of idleness. The backlight checking button worked fine though.

**Comment by tsujan** [comment]
More info and correction (important):

My default setting is so that an external monitor is on and the laptop monitor is off. I turned the laptop monitor on and backlight idleness didn't work. However, I changed the default so that the laptop monitor was on too, logged out and logged it again. *This time it worked.*

So, for some reason, it won't work if the laptop monitor is turned on but not as the default monitor setting. It works when the laptop monitor is on *by default*.

**Comment by tsujan** [comment]
There's also another minor issue:

Provided that the laptop monitor is on by default, backlight change requires "Enable Idleness Watcher" to be checked. That's OK but (1) the backlight groupbox isn't disabled when "Enable Idleness Watcher" is not checked and (2) IMHO, with this feature, the GUI needs to be changed so that the checkbox "Enable Idleness Watcher" is above both groupboxes and doesn't belong to the first one -- or even better, *the second groupbox could be inside the first one*.

**Comment by selairi** [comment]
> There's also another minor issue:
> 
> Provided that the laptop monitor is on by default, backlight change requires "Enable Idleness Watcher" to be checked. That's OK but (1) the backlight groupbox isn't disabled when "Enable Idleness Watcher" is not checked and (2) IMHO, with this feature, the GUI needs to be changed so that the checkbox "Enable Idleness Watcher" is above both groupboxes and doesn't belong to the first one -- or even better, it could remain where it is but _the second groupbox could be inside the first one_.

I have just changed the interface:
bajarbrillo

**Comment by selairi** [comment]
> More info and correction (important):
> 
> My default setting is so that an external monitor is on and the laptop monitor is off. I turned the laptop monitor on and backlight idleness didn't work. However, I changed the default so that the laptop monitor was on too, logged out and logged it again. _This time it worked._
> 
> So, for some reason, it won't work if the laptop monitor is turned on but not as the default monitor setting. It works when the laptop monitor is on _by default_.

Sorry, I cannot reproduce that behavior. Could you please send me the output of `ls /sys/class/backlight/`? Thanks.

**Comment by tsujan** [comment]
```
$ ls /sys/class/backlight/
intel_backlight

$ ls /sys/class/backlight/intel_backlight/
actual_brightness  brightness  max_brightness  subsystem  uevent
bl_power           device      power           type
```
I don't think the problem is there. It's that the new feature won't "see" that the laptop monitor if it's turned on only *after login*, even if the feature is enabled after the monitor is turned on.

In comparison, if I select "Turn off monitor(s)" in front of "When idle then:", the laptop monitor will be recognized, whether it's on by default or only turned on after login.

**Comment by tsujan** [comment]
By turning on/off I mean checking/unchecking "Enable this display" in Monitor Settings (not using a physical button).

**Comment by selairi** [comment]
> I don't think the problem is there. It's that the new feature won't "see" that the laptop monitor if it's turned on only _after login_, even if the feature is enabled after the monitor is turned on.

@tsujan Yes, you found the bug. The power manager has to "listen" the LXQt::Backlight signals. I will push when I finish the changes.

**Comment by selairi** [comment]
@tsujan I have just uploaded the changes. I think that it can works properly.

**Comment by tsujan** [comment]
@selairi 
I'm afraid it still doesn't work with the above-mentioned scenario. The steps to reproduce the problem:

 1. With laptop display enabled, set backlight idle time to 20 seconds.
 2. Disable laptop display in Monitor Settings, click Apply *and then click Save* (of course, you need an external monitor attached to the laptop).
 3. Log out, log in and re-enable laptop display in Monitor Settings.
 4. Wait 20 seconds or more.

Then, nothing will happen.

**Comment by selairi** [comment]
> The steps to reproduce the problem:
> 
>     1. With laptop display enabled, set backlight idle time to 20 seconds.
> 
>     2. Disable laptop display in Monitor Settings, click Apply _and then click Save_ (of course, you need an external monitor attached to the laptop).
> 
>     3. Log out, log in and re-enable laptop display in Monitor Settings.
> 
>     4. Wait 20 seconds or more.
> 
> 
> Then, nothing will happen.

@tsujan First, I followed those steps and the lxqt-powermanager did not change the backlight.  Next, I started to check the code and then, I realized that I had to read the code of LXQt::Backlight. Finally, I noticed that LXQt::Backlight sets isBacklightAvailable() when it is created. As a consequence, when LXQt::Backlight is created and deleted, lxqt-powermanager will work properly. ☺☺☺☺

I have just "pushed" it.

Thanks

**Comment by tsujan** [comment]
@selairi 
With your latest commit, it works like a charm :) Very nice job!

Only a small thing remains:

Would you please change "Enable change backlight" to "Enable Backlight Change"? (Swap "change" and "backlight" and also, capitalize the initials like its top groupbox.)

**Comment by selairi** [comment]
> Would you please change "Enable change backlight" to "Enable Backlight Change"? (Swap "change" and "backlight" and also, capitalize the initials like its top groupbox.)

Done. @tsujan I would like to merge this PR in 2 days. Will you give me your blessings?

**Comment by selairi** [comment]
I would also like to merge the next PR:
[https://github.com/lxqt/lxqt-panel/pull/1385](https://github.com/lxqt/lxqt-panel/pull/1385)
GTM?

**Comment by tsujan** [comment]
GTM

@selairi, please merge it if it's finished. Git users will give us more feedback about this nice feature.

**Pull request merged**
