### PR TITLE
Control power, suspend and hibernate actions

### PR DESCRIPTION
**Pull request by selairi**
This PR fix the issue: [https://github.com/lxqt/lxqt-powermanagement/issues/191](https://github.com/lxqt/lxqt-powermanagement/issues/191)

### CODE REVIEW

**Comment by tsujan** [comment]
I have a power key and this PR works with it without problem. So, as far as I could test, GTM.

But the new section has the generic "application" icon here (its name may be different in other icon sets). IMO, it's better to give it a proper "power" icon that can be found in important icon sets.

**Comment by tsujan** [comment]
@selairi 
What about `system-shutdown`? It's in all important icon sets and, IMHO, conveys the meaning.

**Comment by tsujan** [comment]
Moreover, in many laptops I've seen, the power button has a symbol like `system-shutdown` on it.

**Comment by selairi** [comment]
> @selairi
> What about `system-shutdown`? It's in all important icon sets and, IMHO, conveys the meaning.

OK. I will change it.

**Comment by tsujan** [comment]
> OK. I will change it.

Yes, please do it. "keyboard" is specific to the gnome icon sets, while "system-shutdown" can be find in all icon sets. Moreover, this isn't necessarily about keyboards.

**Pull request merged**
