### PR TITLE
iconproducer: Add percentage to generated icon

### PR DESCRIPTION
**Pull request by palinek**
- before
screenshot  screenshot screenshot
- after
screenshot screenshot screenshot

@lxqt/lxqt Note: I'm not a designer, feel free to enhance the graphics

### CODE REVIEW

**Comment by palinek** [comment]
ref. lxqt/lxqt-powermanagement#231

**Comment by stefonarch** [comment]
Found a second issue: 
1) right click > configure 
2) select "use system icon", works
3) unselect it : it doesn't switch back immediately but only when updated again, up to some minute.

**Comment by palinek** [comment]
@stefonarch Fixed the (old)100% bug

**Comment by stefonarch** [comment]
Nice, thanks, so it was never noticed without the  numbers? 

My 2 cents:
* some smaller size, for the numbers, with a % sign?
* the minus sign. I first thought it was a graphical glitch or imperfection, because it's spilt by the green circle. But both look out of place somehow, in the center they were perfect. Another way to inform about  charging/discharging should be found IMHO. Colors?
* Is it possible to have both (ore even more) icons, to choose from in the settings, keeping also the old one?
* And as said before, in the tooltip showing the same doesn't make much sense, but showing remaining time would be liked by many, even if  this info is often not really reliable - seeing: "3,5 hours power left" can be more useful than "89%."

**Comment by palinek** [comment]
> it was never noticed without the numbers?

Yes. It was there (hidden) intentionally, because of usage of the svg-path-arc...

> the minus sign.

I used the pre-existing graphics, but just moved it to the left/right-upper corner, because leaving them underneath the percentage number was awkward.

> Is it possible to have both (ore even more) icons, to choose from in the settings, keeping also the old one?

I don't think it is worth the hassles and code complication.

> but showing remaining time would be liked by many

Added to tooltip.

**Comment by slidinghotdog** [comment]
> Another way to inform about charging/discharging should be found IMHO. Colors?

- i think using colors could be a bit confusing, i associate it with available charge rather than charging status, like having green circle with more than 2/3, yellow for more than 1/3 and red for less than 1/3.

- Up/down arrows?

- lightning bolt when charging, nothing when discharging, that's how it shows on my phone, and i think it's good.

**Comment by stefonarch** [comment]
> * lightning bolt when charging, nothing when discharging, that's how it shows on my phone, and i think it's good.

I think this is the most suitable, or colors for the +/i signs. But we shouldn't overload the icon, we already have eventually the "pause" emblem when idleness checks are paused. A mockup, I'm not at all familiar with svg:

schermata-01-15-08-51

**Comment by tsujan** [comment]
I haven't tried it yet but I think the problem is that we can't include several details in an icon that can be small. IMO, the percent sign can be removed because it makes the text too small. @palinek's first design (in his screenshots) was better; only the plus and minus signs could be raised to the top layer, maybe with different colors, as @stefonarch suggested. There's no space for ⚡.

**Comment by stefonarch** [comment]
For me without the % it looks too much like a [street sign](https://warnaufkleber24.de/media/catalog/product/cache/1/thumbnail/65x/040ec09b1e35df139433887a97daa66f/1/6/16115_geschwindigkeitszeichen_tempolimit_50_km_h.jpg.pagespeed.ce.tPpNTdJWnM.jpg), can't help.

**Comment by tsujan** [comment]
> For me without the % it looks too much like a street sign

LOL!

Personally, I think we'd better not take complaints about showing the number too seriously; otherwise, we might ruin the current neat design. Custom command plugin exists.

**Comment by tsujan** [comment]
Or we could change the design completely, so that there's room for the text:

battery

**Comment by stefonarch** [comment]
Had the same idea, if we change than better a new one, maybe alongside with the old one which many users are familiar with and which has a particular nice design.

**Comment by tsujan** [comment]
I agree that keeping the old icon and adding a new one with the text is the best approach. The old icon isn't designed to include text.

But doing it will need time and motivation. I, for one, don't understand the urgency of showing the percentage on the icon or beside it.

**Comment by stefonarch** [comment]
Anyway, the now  improved tooltip is nice and should be merged - provide info when asked for.

**Comment by palinek** [comment]
Added new design of icon and updated the config GUI to let user choose between those 3.
Now with this we could easily change the code to get the theme icons, the preexisting one (w/o change), the circle one with text percentage, the battery one.
screenshot

**Comment by tsujan** [comment]
> Added new design of icon

The left design is very nice. The right one makes the text unreadable, and its reddish color is too alarming.

I think the translucent white background isn't needed with this design — the icon is also more attractive without it — and the whole icon can be made opaque.

**Comment by palinek** [comment]
> The left design is very nice. The right one makes the text unreadable, and its reddish color is too alarming.

Both are the same design :). It is using the same green gradient, which is used in the pre-existing circle icon. The gradient is overlapped by pure red color (when discharging) with changing opacity from 0.0 - 60% to 1.0 - 0%. Maybe we can decrease the  60% level when the red begins to come into play.

**Comment by tsujan** [comment]
I got it after seeing the code. IMHO, red is too alarming and makes the text hard to read on thin panels. Yellow?

**Comment by palinek** [comment]
This is with 30% breakpoint:
screenshot
screenshot
screenshot
screenshot

**Comment by tsujan** [comment]
> This is with 30% breakpoint:

They seem OK.

I'd remove the translucent square background and make the icon opaque, but I guess it's a matter of taste.

**Comment by palinek** [comment]
> I'd remove the translucent square background and make the icon opaque

Then:
1. we probably should move the charging sign into the battery completely to avoid invisibleness on particular backgrounds
2. on some (green) backgrounds the battery can become hardly visible

Am I too cautious?

**Comment by tsujan** [comment]
> Am I too cautious?

No, you think logically, while I ignore rare special cases. You're right.

Perhaps we'd better merge it as it; later, we could think about aesthetic details.

**Comment by palinek** [comment]
> Perhaps we'd better merge it as it is

OK... so I'll update the PR to include 4 icon types:
- from theme
- pre-existing circle
- new circle+percentage
- new battery

**Comment by tsujan** [comment]
Would be wonderful.

**Comment by stefonarch** [comment]
Here the flash emblem isn't shown when plugged in (changed only text from _bolder_ to _normal_ - bold looks to strong for my taste).
schermata-01-18-17-35

**Comment by stefonarch** [comment]
When full charged the + emblem  in the enhanced circle is trasformed in a dot which is hard to understand. While testing different sizes and colors ecc I stumbled upon 
```
 battery
    present:             yes
    rechargeable:        yes
    state:               pending-charge
```
and the icon tells "empty (97%)" and  no +sign is shown.
schermata-01-18-18-27-01

**Comment by palinek** [comment]
> I'd remove the translucent square background and make the icon opaque

While I'm on it... added the 5th type (just the "opaque" modification of the "battery" one):
screenshot

Now I think this should be ready to ship.

**Comment by stefonarch** [comment]
There are some small issues left IMHO:

* the mentioned dot when full and plugged in in circle_enhanced
* text "normal "and font-size "80" ? Actually it's quite strong compared with other icons that show numbers, specially in circle_enhanced.
* Naming (because hard to translate): circle-enhanced → "circle with percentage" or "circle with %"? Discard "built in"? It's not really necessary.
* Adding also "Battery without %" ?

**Comment by stefonarch** [comment]
Slightly reduced text,  +/i and circle (full charged and plugged in) symbols, dark red color:
schermata-01-20-20-23 schermata-01-20-20-23-01
schermata-01-20-21-26

**Comment by tsujan** [comment]
> Slightly reduced text, +/i and circle (full charged and plugged in) symbols, dark red color:

IMHO, if a sign needs to be red, it'll be the minus sign.

Apart from the look, if the PR works fine now, please merge it. I agree that the appearance needs improvement and I have a plan to make a PR.

**Comment by palinek** [comment]
> if the PR works fine now, please merge it. I agree that the appearance needs improvement and I have a plan to make a PR.

In opening comment I said directly, that I'm no designer... 
@stefonarch are you OK with merging this and the appearance will be fine-tuned in following PR (by you or by tsujan)?

**Comment by stefonarch** [comment]
> @stefonarch are you OK with merging this and the appearance will be fine-tuned in following PR (by you or by tsujan)?

I am, but also the naming should be reconsidered as I mentioned

**Comment by tsujan** [comment]
> In opening comment I said directly, that I'm no designer...

IMO, the design is OK. I'll make only minor modifications, with @stefonarch's help.

**Pull request merged**
