### PR TITLE
Inform users of XF86 keys under Wayland

### PR DESCRIPTION
**Pull request by tsujan**
Closes https://github.com/lxqt/lxqt-powermanagement/issues/381

### CODE REVIEW

**Review by stefonarch — COMMENTED** [review]
I think the text should make it more clear that those settings are x11 only.
"...have to be configured...instead" ?

**Comment by tsujan** [comment]
Made it more concise: "Note: Under Wayland, power keys are configured by the compositor instead."

**Review by stefonarch — APPROVED** [review]
Ok. Btw I noticed that under wayfire  the powerkey can be configured with the wcm GUI

**Comment by tsujan** [comment]
Personally, I may use only the "shutdown" key on my keyboard (when something bad happens) and, sometimes, multimedia keys. For some reason, whether under X11 or Wayland, they work without me having configured them ;) The shutdown key makes the laptop shut down cleanly — unless a kernel bug freezes everything, in which case, it'll forcefully power off the computer if pressed for 4 seconds.

**Comment by stefonarch** [comment]
The shutdown key will just kill the session and all applications I think, I like to use it as shortcut for `lxqt-leave`. Until now I haden't configured it in other compositors than labwc, so it happened that I shut down the system by mistake instead of choosing logout from the menu.

**Comment by tsujan** [comment]
> The shutdown key will just kill the session and all applications

Here, it's the same special key that starts up the computer. It also causes a clean shutdown, exactly like shutting down by using lxqt-leave, but without prompt. That's its default job, defined somewhere independently of any DE.

**Comment by stefonarch** [comment]
> exactly like shutting down by using lxqt-leave

Never tested here, when I hit it accidentally it seemed too fast to me. 
Probably it's handled by the defaults of `logind.conf`: `#HandlePowerKey=poweroff`.

**Pull request merged**
