### PR TITLE
Small modification to battery icons

### PR DESCRIPTION
**Pull request by tsujan**
This PR is only about the appearance — after https://github.com/lxqt/lxqt-powermanagement/pull/294. It doesn't change the functionality.

### CODE REVIEW

**Review by stefonarch — COMMENTED** [review]
In my experiments I made the text some smaller, 44, I liked it more.

But the "laying" flash above is not good  IMHO -  a flash never lies, and in the non-opaque it's also hardly visible.
It is also hardly visible in master, but better. 
Maybe we could think about something completely different, for example a gold border around the battery? A golden circle behind it?

**Comment by tsujan** [comment]
> In my experiments I made the text some smaller, 44, I liked it more.

44 is too small here. See the current value like a compromise.

> But the "laying" flash above is not good IMHO

The flash was almost invisible here; moreover, it overlapped "100". Now it's visible and there's no overlapping:

flash

The problem is that various combinations are possible: the panel can be dark, light, translucent, thin or thick. Maybe we could make the flash a little bigger and make its color a little darker. I'll experiment with it.

But, to me, the main problem is a bug that was introduced in https://github.com/lxqt/lxqt-powermanagement/pull/294: if you've chosen a built-in icon and (1) change it to the theme icon and (2) change it again to *the same* built-in icon, the tray icon won't be updated at (2). I think it has something to do with the new cache @palinek added but I'm still not sure.

**Comment by tsujan** [comment]
I made the flash as big as possible and gave it a thicker red border. I don't think it can be missed now:

flash2

> for example a gold border around the battery?

I tested it. It can be almost invisible when the icons is small.

**Comment by tsujan** [comment]
The green gradient wasn't correct. It started at top left and ended at bottom right. Fixed now:

flash3

**Comment by stefonarch** [comment]
The colors are perfect  now, but I've still problems to recognize it as a flash, because of it's laying position...

schermata-01-21-21-14


> the tray icon won't be updated

confirmed. Another /small) issue is the preview doesn't show 100% change of the  +  sign to circle in circle icons.

> it overlapped "100".

I was also thinking not to show 100 but something else (or nothing), so the flash wouldn't overlap and could stay well beside 01-99

**Comment by tsujan** [comment]
> but I've still problems to recognize it as a flash

Your screenshot shows that you aren't using the latest commit.

**Comment by stefonarch** [comment]
It was ```
git show
commit 8a1be130c5c1f1bd9796110521abdea9afa0b26b 
```
but  yes I forgot to restart the module:

![schermata-01-21-21-55](https://user-images.githubusercontent.com/10681413/150599081-30d35b98-871f-4d1d-8715-fa421f7e5cf2.png)


But as people are used to vertical flash icons I'm not convinced.

**Comment by tsujan** [comment]
> But as people are used to vertical flash icons I'm not convinced.

A clearly visible vertical flash icon is possible only with a vertical battery icon, for which we would need a vertical text, which would complicate things, especially because some people may find the latter unusual.

The flash is completely visible in your screenshot and is much better than the current master.

**Comment by tsujan** [comment]
>  Another (small) issue is the preview doesn't show at 100% the change of the + sign to the small full circle in circle icons.

Yes, but it isn't a full circle anymore but a small yellow star at the middle top:

star

**Comment by stefonarch** [comment]
Nice!

**Comment by tsujan** [comment]
* Fortunately, the above-mentioned bug wasn't related to the recent changes — @palinek's new cache has no problem.
 * I saw lots of battery icons with horizontal flashes on the Internet. I also experimented with other shapes but none of them was as clear as the current flash.
 * Finally, I logged into KDE and saw that its Plasma battery icon couldn't be a source of inspiration for us; its inline text was a joke.

So, I'm convinced that this is the best we can get.

**Comment by stefonarch** [comment]
ok, merge it :)

**Review by stefonarch — APPROVED** [review]

**Comment by tsujan** [comment]
I tested this variation for hours and really liked it:

Icon

Because of its two colors, it has a higher visibility against all backgrounds and with all sizes. On my translucent thin panel, it looks less pixelized too:

panel

That being said, don't hesitate to tell me if you don't like it.

**Comment by stefonarch** [comment]
If I'd to choose I'd choose the previous one, with the red border. 
And I'm about to get used to see the laying flash ;)

**Comment by tsujan** [comment]
I try to change your mind, but only once ;)

In this screenshot, the desktop wallpaper has changed. Now, the red flash contributes to the visibility more than in my previous screenshot, where the wallpaper was dark:

panel1

You'll loose this good contrast ;)

**Comment by stefonarch** [comment]
You're hard, you've won :)

**Comment by tsujan** [comment]
You won't regret it; this is the best compact design on the planet ;) I'll add the commit, squash and merge.

BTW, I found the fix for the above-mentioned bug too :) Will open an issue and make another PR for it.

**Comment by stefonarch** [comment]
Sure you've also baked a circle icon already ;)

**Comment by tsujan** [comment]
Found the fix only by chance; wanted to prevent a high memory usage and, in the middle of the process, suspected that the current cache (as well as the old one) might have a problem with `QIcon`. My guess was right.

**Comment by stefonarch** [comment]
> Yes, but it isn't a full circle anymore but a small yellow star at the middle top:
> 
> star

I was playing with the circle+percentage icon. Text smaller so that it fits in the circle, less opacity, as in second image. But those +/i symbols... :

schermata-02-25-20-54

I think they are redundant -  they are coming from another design and are out of place here. What is needed is to show "plugged in or not", so what about showing the same star also when charging and nothing else?


schermata-02-25-21-16

**Comment by tsujan** [comment]
Tastes differ. Your proposal is acceptable but the current icons are good too. One can also say that a minus/plus sign immediately shows what's happening; it may be logically redundant but is practically helpful.

**Comment by stefonarch** [comment]
To me the actual one looks really unfinished, I can't help. Text and symbols too heavy and too big.

**Comment by tsujan** [comment]
> Text and symbols too heavy and too big.

If you used a thin panel, a smaller text would be hardly visible. If I correctly remember, I made it smaller than @palinek's version; a text smaller than this could be problematic, IMO.

Personally, I use the battery icon. I think there are enough options for everyone. But if someone can make the circular icons better, why not?

**Comment by tsujan** [comment]
Yes, it was `font-size='100' font-weight='bolder'` and I made it `font-size='80' font-weight='bold'`; the smallest, clearly visible text possible.

**Pull request merged**
