### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-powermanagment/) for LXQt Configuration/lxqt-config-powermanagement.

### CODE REVIEW

**Comment by stefonarch** [comment]
@tsujan Here we have this numerusform thing again, qt removes them and translators readd them.
I think merging is good, I'm away now.

**Comment by tsujan** [comment]
> t removes them and translators readd them

The rule of thumb: Qt is correct, unless a bug is reported. If Qt removes them, then they shouldn't be used with the string in question.

Do you need more time before I start releasing? I could wait if you do.

**Comment by stefonarch** [comment]
There are other translations here to merge, I'm away until this evening, do what you consider ok.

**Comment by tsujan** [comment]
I ran `lxqt-transupdate` inside this branch and Qt changed nothing. So, it's OK.

**Pull request merged**
